function getImages(){
    var objs = document.getElementsByTagName("img");
    for(var i=0;i<objs.length;i++){
        objs[i].onclick=function(){
            alert(this.src);
            document.location="myweb:imageClick:"+this.src;
        };
    };
    return objs.length;
};


//<div class="main-wrap content-wrap\">
//<div class="headline\">\n\n<div class=\"img-place-holder\"></div>\n\n\n\n</div>\n\n<div class=\"content-inner\">\n\n\n\n\n<div class=\"question\">\n<h2 class=\"question-title\">如何练胸肌？</h2>\n\n<div class=\"answer\">\n\n<div class=\"meta\">\n<img class=\"avatar\" src=\"http://pic1.zhimg.com/491960848_is.jpg\">\n<span class=\"author\">陈柏龄，</span><span class=\"bio\">公众号：陈柏龄的酱油台</span>\n</div>\n\n<div class=\"content\">\n<p>说实话，这个问题依然有点大。如果换成有什么动作可以练「胸肌」？我想更好。</p>\r\n<p>细节和具体的规则就不多说了。就说说动作好了。</p>\r\n<p>锻炼胸肌，最简单就是俯卧撑。</p>\r\n<p>而在健身房中，要高强度地刺激胸肌，那么依然是两个黄金动作最经典。</p>\r\n<p>一是卧推，一是飞鸟。卧推主要刺激胸大肌，飞鸟是刺激胸肌中缝，形成「乳沟」。</p>\r\n<p>从这两种动作又可以分化出许多的变化来。</p>\r\n<p><strong>动作的变化在图片的左下角，不明白的可以自己搜视频。</strong></p>\r\n<p><strong>一、卧推</strong></p>\r\n<p>卧推有好几种划分，</p>\r\n<p>从卧推的角度来看，可以分为上斜卧推、平板卧推和下斜卧推。</p>\r\n<p>从器械上来看，可以分为杠铃卧推和哑铃卧推。 而杠铃卧推中又有宽距握法和窄距握法的区分。</p>\r\n<p><strong>1.平板杠铃卧推（宽握）</strong></p>\r\n<p>需要注意三点，一是卧推时杠铃需要自然推起（下放在胸部而顶点在肩关节上方），二是杠铃要尽量下放到贴近胸部的位置再推起，三是卧推时杠铃下放触及的应该是乳头附近的位置。</p>\r\n<p>很多新手卧推时，推起放下往往不是垂直的，下放往往放到肩部附近，这就是错误的推法，这样卧推是刺激不到胸肌的。</p>\r\n<p><img class=\"content-image\" src=\"http://pic2.zhimg.com/70/91d7b969adf6f9b08c9bac9515947e49_b.jpg\" alt=\"\" /></p>\r\n<p><strong>2.上斜板杠铃卧推（宽握）</strong></p>\r\n<p>其实就是将平板的角度向上倾斜 45~60 度</p>\r\n<p>上斜板卧推需要注意的是，下放的位置不是乳头附近，而是下放到锁骨即可。</p>\r\n<p><img class=\"content-image\" src=\"http://pic3.zhimg.com/70/7be1dd298a292e037dbc4aa8f629a66a_b.jpg\" alt=\"\" /></p>\r\n<p><strong>3.下斜板哑铃卧推（宽握）</strong></p>\r\n<p>下斜卧推杠铃是下放到乳头往下 3cm 的位置，但是远没有到腹部。</p>\r\n<p><img class=\"content-image\" src=\"http://pic3.zhimg.com/70/8c8c9d17e371a3e75c7d16ef2bc2766e_b.jpg\" alt=\"\" /></p>\r\n<p><strong>4.窄握</strong></p>\r\n<p>下面这是平板杠铃卧推（窄握）。窄握是提高卧推力量的很好的方法，和宽握相比，窄握中肱三头肌受力更大，卧推力量遇到瓶颈时，可以用窄握来突破。上斜和下斜的窄握就不贴了。</p>\r\n<p><img class=\"content-image\" src=\"http://pic1.zhimg.com/70/6bf17972f0cc1e2d799a7f224ce5a300_b.jpg\" alt=\"\" /></p>\r\n<p><strong>5.哑铃卧推</strong>，方法与杠铃卧推类似，无非就是上斜下斜平板，不过哑铃卧推需要更多的平衡性。</p>\r\n<p><strong>二、飞鸟</strong></p>\r\n<p><strong>1.绳索飞鸟（又叫龙门十字夹胸）</strong></p>\r\n<p>这应该是对胸肌中缝刺激最大的动作了。</p>\r\n<p>个人认为，这个动作比较高级，我当时是健身 4 个月后才开始练这个动作的。</p>\r\n<p>这个动作也有很多种变化，具体要自己体会了。</p>\r\n<p>这个动作需要注意的是，手要尽量打开，肘关节微曲，不要用腰背过分的借力。</p>\r\n<p><img class=\"content-image\" src=\"http://pic2.zhimg.com/70/57fe580471738a57e53adc7f28edd7c9_b.jpg\" alt=\"\" /></p>\r\n<p><strong>2.哑铃飞鸟</strong></p>\r\n<p>哑铃飞鸟也是分成上斜、下斜、平板。这里就不全部贴出来了，就贴一个平板飞鸟好了。</p>\r\n<p>做哑铃飞鸟时你去想象你前面有个人，你要去「拥抱」他，就是用那种拥抱的感觉去练飞鸟就对了。</p>\r\n<p><img class=\"content-image\" src=\"http://pic2.zhimg.com/70/5f1bbc94f03ee36a8801ac0f7b96a945_b.jpg\" alt=\"\" /></p>\r\n<p><strong>三、双臂杆屈伸</strong></p>\r\n<p>这是在飞鸟和卧推之外的动作，根据身体倾向状况，刺激的肌肉部位也不同，身体越前倾，胸大肌的刺激越大，越直立，就越容易刺激肱三头肌。</p>\r\n<p><img class=\"content-image\" src=\"http://pic1.zhimg.com/70/6dbf553a35237038835d86629807c7a8_b.jpg\" alt=\"\" /></p>\n</div>\n</div>\n\n\n<div class=\"view-more\"><a href=\"http://www.zhihu.com/question/19569125\">查看知乎讨论<span class=\"js-question-holder\"></span></a></div>\n\n</div>\n\n\n</div>\n</div>"